branch-defaults:
  develop:
    environment: analytics-develop
deploy:
  artifact: Dockerrun.aws.json
global:
  application_name: develop
  default_ec2_keyname: endurance
  default_platform: docker
  default_region: us-west-2
  profile: null
  sc: git
